server:
  port: 8080
  forward-headers-strategy: framework

spring:
  main:
    banner-mode: 'off'

  jmx:
    enabled: true

  security:
    user:
      name: ${docker-secrets.frog_admin_user}
      password: ${docker-secrets.frog_admin_password}

#  boot:
#    admin:
#      notify:
#        slack:
#          enabled: false
#          webhook-url: ${docker-secrets.slack_webhook}
#          message: "#{instance.registration.name} gone from #{lastStatus} to *#{event.statusInfo.status}*"

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    root: INFO
    com.frogdevelopment: DEBUG
