server:
  port: 8080
  forward-headers-strategy: framework

spring:
  main:
    banner-mode: 'off'

  security:
    user:
      name: ${docker-secrets.frog_admin_user}
      password: ${docker-secrets.frog_admin_password}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      enabled: true

logging:
  level:
    root: WARN
