server:
  port: 8080
  forward-headers-strategy: framework

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
    health:
      enabled: true
    loggers:
      enabled: true

logging:
  level:
    root: INFO

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      user.name: ${docker-secrets.frog_admin_user}
      user.password: ${docker-secrets.frog_admin_password}
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${docker-secrets.frog_admin_user}:${docker-secrets.frog_admin_password}@support-registry:8080/eureka/

spring:
  application:
    name: support-administration
  main:
    banner-mode: 'off'

  security:
    user:
      name: ${docker-secrets.frog_admin_user}
      password: ${docker-secrets.frog_admin_password}

