server:
  forward-headers-strategy: framework

## ROUTING CONFIGURATION
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'/api/' + serviceId.replace('-service', '') + '/**'"
          filters:
            - name: RewritePath
              args:
                regexp: "'/api/' + serviceId.replace('-service', '') + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
