server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    loggers:
      enabled: true

logging:
  level:
    root: INFO

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: ${spring.application.name}
    metadata-map:
      user.name: ${docker-secrets.frog_admin_user}
      user.password: ${docker-secrets.frog_admin_password}
  client:
    service-url:
      defaultZone: http://${docker-secrets.frog_admin_user}:${docker-secrets.frog_admin_password}@support-registry:8080/eureka/

spring:
  application:
    name: support-gateway
  main:
    banner-mode: 'off'

  cloud:
    ## ROUTING CONFIGURATION
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'/api/' + serviceId.replace('-service', '') + '/**'"
          filters:
            - name: RewritePath
              args:
                regexp: "'/api/' + serviceId.replace('-service', '') + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
