server:
  port: 8080

spring:
  main:
    banner-mode: 'off'

  security:
    user:
      name: ${docker-secrets.frog_admin_user}
      password: ${docker-secrets.frog_admin_password}

management:
  server:
    port: 8081

logging:
  level:
    root: WARN
