server:
  port: 8080

spring:
  main:
    banner-mode: 'off'

  security:
    user:
      name: ${docker-secrets.frog_admin_user}
      password: ${docker-secrets.frog_admin_password}

  jmx:
    enabled: true

management:
  server:
    port: 8081
  endpoint:
    env:
      post:
        enabled: true # allow the Environment Manager for Context refresh
    health:
      show-details: always
    restart:
      enabled: true

logging:
  level:
    root: INFO
    com.frogdevelopment: DEBUG
