server:
  port: 8080

spring:
  main:
    banner-mode: 'off'

  security:
    user:
      name: ${docker-secrets.frog_admin_user}
      password: ${docker-secrets.frog_admin_password}

  cloud:
    config:
      fail-fast: true
      server:
        secrets:
          order: 1
        git:
          order: 2
          uri: ${docker-secrets.git_uri}
          default-label: ${GIT_LABEL:master}
          refresh-rate: 10

  profiles:
    active: git, secrets

management:
  server:
    port: 8081
  endpoint:
    health:
      enabled: true
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: WARN
