server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    loggers:
      enabled: true

logging:
  level:
    root: INFO

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: ${spring.application.name}
    metadata-map:
      user.name: ${docker-secrets.frog_admin_user}
      user.password: ${docker-secrets.frog_admin_password}
  client:
    service-url:
      defaultZone: http://${docker-secrets.frog_admin_user}:${docker-secrets.frog_admin_password}@support-registry:8080/eureka/

spring:
  application:
    name: support-config-server
  main:
    banner-mode: 'off'

  security:
    user:
      name: ${docker-secrets.frog_admin_user}
      password: ${docker-secrets.frog_admin_password}

  cloud:
    config:
      fail-fast: true
      server:
        secrets:
          order: 1
        git:
          order: 2
          uri: ${docker-secrets.git_uri}
          default-label: ${GIT_LABEL:master}
          refresh-rate: 10
          ignore-local-ssh-settings: true
          host-key-algorithm: ecdsa-sha2-nistp256
          host-key: ${docker-secrets.host-key}
          strict-host-key-checking: false
          private-key: ${docker-secrets.private-key}
          clone-on-start: true
          force-pull: true

  profiles:
    active: git, secrets
