name: Java CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java 14
        uses: joschi/setup-jdk@v2
        with:
          java-version: '14'

      - name: Compile
        run: ./gradlew classes

      - name: Test
        run: ./gradlew test -x bootBuildInfo

      - name: Containerize
        run: ./gradlew jib -Djib.to.auth.username=${{ secrets.DOCKER_USR }} -Djib.to.auth.password=${{ secrets.DOCKER_PSW }} -Djib.console='plain' -x bootBuildInfo
